export const ERROR_CODES = {
  VALIDATION_ERROR: "E001",
  MISSING_FIELD: "E002",
  INVALID_INPUT: "E003",
  INVALID_EMAIL: "E004",
  INVALID_PHONE: "E005",
  INVALID_PRICE: "E006",
  INVALID_QUANTITY: "E007",

  NOT_FOUND: "E404",
  USER_NOT_FOUND: "E404_USER",
  PRODUCT_NOT_FOUND: "E404_PRODUCT",
  ORDER_NOT_FOUND: "E404_ORDER",
  SUPPLIER_NOT_FOUND: "E404_SUPPLIER",
  ORDER_ITEM_NOT_FOUND: "E404_ORDER_ITEM",

  UNAUTHORIZED: "E401",
  FORBIDDEN: "E403",
  INVALID_CREDENTIALS: "E401_CREDS",
  TOKEN_EXPIRED: "E401_TOKEN",
  INVALID_TOKEN: "E401_INVALID",

  INSUFFICIENT_STOCK: "E400_STOCK",
  DUPLICATE_ENTRY: "E409",
  DUPLICATE_EMAIL: "E409_EMAIL",
  ORDER_ALREADY_CONFIRMED: "E409_ORDER_CONFIRMED",
  ORDER_ALREADY_DELIVERED: "E409_ORDER_DELIVERED",
  SUPPLIER_NOT_VERIFIED: "E403_SUPPLIER",
  PRODUCT_OUT_OF_STOCK: "E400_OUT_STOCK",

  DATABASE_ERROR: "E503",
  DATABASE_CONNECTION_FAILED: "E503_CONN",
  DATABASE_QUERY_FAILED: "E503_QUERY",

  INTERNAL_ERROR: "E500",
  SERVICE_UNAVAILABLE: "E503",
  EXTERNAL_API_ERROR: "E502",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export const getStatusFromErrorCode = (code: ErrorCode): number => {
  if (code.startsWith("E404")) return 404;
  if (code.startsWith("E401")) return 401;
  if (code.startsWith("E403")) return 403;
  if (code.startsWith("E409")) return 409;
  if (code.startsWith("E400")) return 400;
  if (code.startsWith("E503")) return 503;
  if (code.startsWith("E502")) return 502;
  return 500;
};
